/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type VideoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "video";
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type Newsletter = {
  _id: string;
  _type: "newsletter";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  subject?: string;
  previewText?: string;
  video?: VideoReference;
  post?: PostReference;
  intro?: BlockContent;
  recipientSelection?: {
    selectionType?: "test" | "audience";
    testEmails?: Array<string>;
  };
  status?: "draft" | "sending" | "sent" | "failed";
  sentAt?: string;
  recipientCount?: number;
  resendBroadcastId?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  cloudinaryPublicId?: string;
  cloudinaryUrl?: string;
  status?: "rendering" | "uploading" | "ready" | "failed";
  errorMessage?: string;
  post?: PostReference;
  format?: "mp4";
  template?: "article-promo" | "article-teaser" | "article-narrated";
  duration?: number;
  width?: number;
  height?: number;
  variants?: Array<{
    variantId?: string;
    surface?: string;
    format?: string;
    url?: string;
    width?: number;
    height?: number;
    _key: string;
  }>;
  renderStartedAt?: string;
  renderedAt?: string;
  inputProps?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type SanityAgentContextReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.agentContext";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  excerpt?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  publishedAt?: string;
  body?: BlockContent;
  voice?: SanityAgentContextReference;
  autoGenerateVideoOnPublish?: boolean;
  voiceoverChunks?: Array<{
    id?: string;
    text?: string;
    audioUrl?: string;
    durationSeconds?: number;
    _key: string;
  }>;
  videoCopy?: {
    kicker?: string;
    headline?: string;
    subhead?: string;
    pullQuote?: string;
    ctaPrimary?: string;
    ctaSecondary?: string;
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssistInstructionTask = {
  _type: "sanity.assist.instructionTask";
  path?: string;
  instructionKey?: string;
  started?: string;
  updated?: string;
  info?: string;
};

export type SanityAssistTaskStatus = {
  _type: "sanity.assist.task.status";
  tasks?: Array<
    {
      _key: string;
    } & SanityAssistInstructionTask
  >;
};

export type SanityAssistSchemaTypeAnnotations = {
  _type: "sanity.assist.schemaType.annotations";
  title?: string;
  fields?: Array<
    {
      _key: string;
    } & SanityAssistSchemaTypeField
  >;
};

export type SanityAssistOutputType = {
  _type: "sanity.assist.output.type";
  type?: string;
};

export type SanityAssistOutputField = {
  _type: "sanity.assist.output.field";
  path?: string;
};

export type AssistInstructionContextReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "assist.instruction.context";
};

export type SanityAssistInstructionContext = {
  _type: "sanity.assist.instruction.context";
  reference?: AssistInstructionContextReference;
};

export type AssistInstructionContext = {
  _id: string;
  _type: "assist.instruction.context";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  context?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityAssistInstructionUserInput = {
  _type: "sanity.assist.instruction.userInput";
  message?: string;
  description?: string;
};

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }
    | ({
        _key: string;
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string;
      } & SanityAssistInstructionContext)
    | ({
        _key: string;
      } & SanityAssistInstructionUserInput)
  >;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityAssistInstructionFieldRef = {
  _type: "sanity.assist.instruction.fieldRef";
  path?: string;
};

export type SanityAssistInstruction = {
  _type: "sanity.assist.instruction";
  prompt?: SanityAssistInstructionPrompt;
  icon?: string;
  title?: string;
  userId?: string;
  createdById?: string;
  output?: Array<
    | ({
        _key: string;
      } & SanityAssistOutputField)
    | ({
        _key: string;
      } & SanityAssistOutputType)
  >;
};

export type SanityAssistSchemaTypeField = {
  _type: "sanity.assist.schemaType.field";
  path?: string;
  instructions?: Array<
    {
      _key: string;
    } & SanityAssistInstruction
  >;
};

export type SanityAgentContext = {
  _id: string;
  _type: "sanity.agentContext";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  version?: string;
  name?: string;
  slug?: Slug;
  groqFilter?: string;
  instructions?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | VideoReference
  | PostReference
  | Newsletter
  | SanityImageAssetReference
  | BlockContent
  | Video
  | AuthorReference
  | SanityAgentContextReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Author
  | Slug
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityAgentContext
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/lib/sanity.queries.ts
// Variable: ALL_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc){    _id,    title,    slug,    publishedAt,    excerpt,    mainImage,    "authorName": author->name,    "preview": *[_type == "video" && post._ref == ^._id && status == "ready" && defined(cloudinaryUrl)] | order(renderedAt desc)[0]{      "previewGifUrl": variants[variantId == "site-preview-gif"][0].url,      "posterUrl": variants[variantId == "site-poster-jpg"][0].url    }  }
export type ALL_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  excerpt: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  authorName: string | null;
  preview: {
    previewGifUrl: string | null;
    posterUrl: string | null;
  } | null;
}>;

// Source: ../web/lib/sanity.queries.ts
// Variable: SINGLE_POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    _id,    title,    slug,    publishedAt,    excerpt,    body,    "authorName": author->name,    "authorImageUrl": author->image.asset->url,    mainImage,    "videos": *[_type == "video" && post._ref == ^._id && status == "ready" && defined(cloudinaryUrl)] | order(renderedAt desc){      _id,      title,      template,      format,      duration,      width,      height,      cloudinaryUrl,      cloudinaryPublicId,      renderedAt,      "podcastUrl": variants[variantId == "podcast-mp3"][0].url,      "posterUrl": variants[variantId == "site-poster-jpg"][0].url,      "youtubeUrl": variants[variantId == "youtube-1080p-mp4"][0].url,        variants[]{variantId, surface, format, url, width, height}    }  }
export type SINGLE_POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  excerpt: string | null;
  body: BlockContent | null;
  authorName: string | null;
  authorImageUrl: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  videos: Array<{
    _id: string;
    title: string | null;
    template: "article-narrated" | "article-promo" | "article-teaser" | null;
    format: "mp4" | null;
    duration: number | null;
    width: number | null;
    height: number | null;
    cloudinaryUrl: string | null;
    cloudinaryPublicId: string | null;
    renderedAt: string | null;
    podcastUrl: string | null;
    posterUrl: string | null;
    youtubeUrl: string | null;
    variants: Array<{
      variantId: string | null;
      surface: string | null;
      format: string | null;
      url: string | null;
      width: number | null;
      height: number | null;
    }> | null;
  }>;
} | null;

// Source: ../web/lib/sanity.queries.ts
// Variable: ALL_VIDEOS_QUERY
// Query: *[_type == "video" && status == "ready" && defined(cloudinaryUrl)] | order(renderedAt desc){    _id,    title,    template,    format,    duration,    width,    height,    cloudinaryUrl,    cloudinaryPublicId,    renderedAt,    "posterUrl": variants[variantId == "site-poster-jpg"][0].url,    "previewGifUrl": variants[variantId == "site-preview-gif"][0].url,      variants[]{variantId, surface, format, url, width, height},    "post": post->{title, slug}  }
export type ALL_VIDEOS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  template: "article-narrated" | "article-promo" | "article-teaser" | null;
  format: "mp4" | null;
  duration: number | null;
  width: number | null;
  height: number | null;
  cloudinaryUrl: string;
  cloudinaryPublicId: string | null;
  renderedAt: string | null;
  posterUrl: string | null;
  previewGifUrl: string | null;
  variants: Array<{
    variantId: string | null;
    surface: string | null;
    format: string | null;
    url: string | null;
    width: number | null;
    height: number | null;
  }> | null;
  post: {
    title: string | null;
    slug: Slug | null;
  } | null;
}>;

// Source: ../web/lib/sanity.queries.ts
// Variable: NEWSLETTER_BY_ID_QUERY
// Query: *[_type == "newsletter" && _id == $id][0]{  _id,  _rev,  title,  subject,  previewText,  intro,  recipientSelection,  status,  sentAt,  recipientCount,  resendBroadcastId,  video->{    _id,    title,    cloudinaryPublicId,    status,    "gifUrl": variants[variantId == "site-preview-gif"][0].url,    "posterUrl": variants[variantId == "site-poster-jpg"][0].url  },  post->{    title,    excerpt,    "slug": slug.current,    publishedAt,    "authorName": author->name  }}
export type NEWSLETTER_BY_ID_QUERY_RESULT = {
  _id: string;
  _rev: string;
  title: string | null;
  subject: string | null;
  previewText: string | null;
  intro: BlockContent | null;
  recipientSelection: {
    selectionType?: "audience" | "test";
    testEmails?: Array<string>;
  } | null;
  status: "draft" | "failed" | "sending" | "sent" | null;
  sentAt: string | null;
  recipientCount: number | null;
  resendBroadcastId: string | null;
  video: {
    _id: string;
    title: string | null;
    cloudinaryPublicId: string | null;
    status: "failed" | "ready" | "rendering" | "uploading" | null;
    gifUrl: string | null;
    posterUrl: string | null;
  } | null;
  post: {
    title: string | null;
    excerpt: string | null;
    slug: string | null;
    publishedAt: string | null;
    authorName: string | null;
  } | null;
} | null;

// Source: ../web/lib/sanity.queries.ts
// Variable: NEWSLETTER_BY_EITHER_ID_QUERY
// Query: *[_type == "newsletter" && _id in [$draftId, $baseId]] | order(_updatedAt desc)[0]{  _id,  _rev,  title,  subject,  previewText,  intro,  recipientSelection,  status,  sentAt,  recipientCount,  resendBroadcastId,  video->{    _id,    title,    cloudinaryPublicId,    status,    "gifUrl": variants[variantId == "site-preview-gif"][0].url,    "posterUrl": variants[variantId == "site-poster-jpg"][0].url  },  post->{    title,    excerpt,    "slug": slug.current,    publishedAt,    "authorName": author->name  }}
export type NEWSLETTER_BY_EITHER_ID_QUERY_RESULT = {
  _id: string;
  _rev: string;
  title: string | null;
  subject: string | null;
  previewText: string | null;
  intro: BlockContent | null;
  recipientSelection: {
    selectionType?: "audience" | "test";
    testEmails?: Array<string>;
  } | null;
  status: "draft" | "failed" | "sending" | "sent" | null;
  sentAt: string | null;
  recipientCount: number | null;
  resendBroadcastId: string | null;
  video: {
    _id: string;
    title: string | null;
    cloudinaryPublicId: string | null;
    status: "failed" | "ready" | "rendering" | "uploading" | null;
    gifUrl: string | null;
    posterUrl: string | null;
  } | null;
  post: {
    title: string | null;
    excerpt: string | null;
    slug: string | null;
    publishedAt: string | null;
    authorName: string | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "post" && defined(slug.current)] | order(publishedAt desc){\n    _id,\n    title,\n    slug,\n    publishedAt,\n    excerpt,\n    mainImage,\n    "authorName": author->name,\n    "preview": *[_type == "video" && post._ref == ^._id && status == "ready" && defined(cloudinaryUrl)] | order(renderedAt desc)[0]{\n      "previewGifUrl": variants[variantId == "site-preview-gif"][0].url,\n      "posterUrl": variants[variantId == "site-poster-jpg"][0].url\n    }\n  }\n': ALL_POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    _id,\n    title,\n    slug,\n    publishedAt,\n    excerpt,\n    body,\n    "authorName": author->name,\n    "authorImageUrl": author->image.asset->url,\n    mainImage,\n    "videos": *[_type == "video" && post._ref == ^._id && status == "ready" && defined(cloudinaryUrl)] | order(renderedAt desc){\n      _id,\n      title,\n      template,\n      format,\n      duration,\n      width,\n      height,\n      cloudinaryUrl,\n      cloudinaryPublicId,\n      renderedAt,\n      "podcastUrl": variants[variantId == "podcast-mp3"][0].url,\n      "posterUrl": variants[variantId == "site-poster-jpg"][0].url,\n      "youtubeUrl": variants[variantId == "youtube-1080p-mp4"][0].url,\n      \n  variants[]{variantId, surface, format, url, width, height}\n\n    }\n  }\n': SINGLE_POST_QUERY_RESULT;
    '\n  *[_type == "video" && status == "ready" && defined(cloudinaryUrl)] | order(renderedAt desc){\n    _id,\n    title,\n    template,\n    format,\n    duration,\n    width,\n    height,\n    cloudinaryUrl,\n    cloudinaryPublicId,\n    renderedAt,\n    "posterUrl": variants[variantId == "site-poster-jpg"][0].url,\n    "previewGifUrl": variants[variantId == "site-preview-gif"][0].url,\n    \n  variants[]{variantId, surface, format, url, width, height}\n,\n    "post": post->{title, slug}\n  }\n': ALL_VIDEOS_QUERY_RESULT;
    '\n  *[_type == "newsletter" && _id == $id][0]{\n  _id,\n  _rev,\n  title,\n  subject,\n  previewText,\n  intro,\n  recipientSelection,\n  status,\n  sentAt,\n  recipientCount,\n  resendBroadcastId,\n  video->{\n    _id,\n    title,\n    cloudinaryPublicId,\n    status,\n    "gifUrl": variants[variantId == "site-preview-gif"][0].url,\n    "posterUrl": variants[variantId == "site-poster-jpg"][0].url\n  },\n  post->{\n    title,\n    excerpt,\n    "slug": slug.current,\n    publishedAt,\n    "authorName": author->name\n  }\n}\n': NEWSLETTER_BY_ID_QUERY_RESULT;
    '\n  *[_type == "newsletter" && _id in [$draftId, $baseId]] | order(_updatedAt desc)[0]{\n  _id,\n  _rev,\n  title,\n  subject,\n  previewText,\n  intro,\n  recipientSelection,\n  status,\n  sentAt,\n  recipientCount,\n  resendBroadcastId,\n  video->{\n    _id,\n    title,\n    cloudinaryPublicId,\n    status,\n    "gifUrl": variants[variantId == "site-preview-gif"][0].url,\n    "posterUrl": variants[variantId == "site-poster-jpg"][0].url\n  },\n  post->{\n    title,\n    excerpt,\n    "slug": slug.current,\n    publishedAt,\n    "authorName": author->name\n  }\n}\n': NEWSLETTER_BY_EITHER_ID_QUERY_RESULT;
  }
}
