import { defineQuery } from 'next-sanity';
import type {
  ALL_POSTS_QUERY_RESULT,
  SINGLE_POST_QUERY_RESULT,
  ALL_VIDEOS_QUERY_RESULT,
  PODCAST_FEED_QUERY_RESULT,
  SITEMAP_QUERY_RESULT,
  PLAYGROUND_VIDEOS_QUERY_RESULT,
  NEWSLETTER_BY_EITHER_ID_QUERY_RESULT,
} from '@/sanity.types';

// Shared fan-out projection: the full Cloudinary variant set on a video doc.
// Reused everywhere the site surfaces the "render once → fan out" derivations.
const VIDEO_VARIANTS_PROJECTION = /* groq */ `
  variants[]{variantId, surface, format, url, width, height}
`;

// All published posts, newest first. `mainImage` is projected as the full image
// object (not a flattened URL) so list views can size/optimize it via urlFor();
// `authorName` is flattened so cards don't need reference resolution. The
// `preview` sub-object pulls the post's newest ready render's GIF + poster
// variants so the home feed can animate a card on hover — the fan-out made
// visible on the most-visited page.
export const ALL_POSTS_QUERY = defineQuery(/* groq */ `
  *[_type == "post" && defined(slug.current)] | order(publishedAt desc){
    _id,
    title,
    slug,
    publishedAt,
    excerpt,
    mainImage,
    "authorName": author->name,
    "preview": *[_type == "video" && post._ref == ^._id && status == "ready" && defined(cloudinaryUrl)] | order(renderedAt desc)[0]{
      "previewGifUrl": variants[variantId == "site-preview-gif"][0].url,
      "posterUrl": variants[variantId == "site-poster-jpg"][0].url
    }
  }
`);

// A single post plus its ready videos (back-referenced — the video doc points
// at the post via `post`, the post does not hold a videos[] array).
export const SINGLE_POST_QUERY = defineQuery(/* groq */ `
  *[_type == "post" && slug.current == $slug][0]{
    _id,
    title,
    slug,
    publishedAt,
    excerpt,
    body,
    "authorName": author->name,
    "authorImageUrl": author->image.asset->url,
    mainImage,
    "videos": *[_type == "video" && post._ref == ^._id && status == "ready" && defined(cloudinaryUrl)] | order(renderedAt desc){
      _id,
      title,
      template,
      format,
      duration,
      width,
      height,
      cloudinaryUrl,
      cloudinaryPublicId,
      renderStartedAt,
      renderedAt,
      "podcastUrl": variants[variantId == "podcast-mp3"][0].url,
      "posterUrl": variants[variantId == "site-poster-jpg"][0].url,
      "youtubeUrl": variants[variantId == "youtube-1080p-mp4"][0].url,
      "siteMp4Url": variants[variantId == "site-mp4"][0].url,
      ${VIDEO_VARIANTS_PROJECTION}
    }
  }
`);

// Every ready video across the site, with a light reference back to its post.
export const ALL_VIDEOS_QUERY = defineQuery(/* groq */ `
  *[_type == "video" && status == "ready" && defined(cloudinaryUrl)] | order(renderedAt desc){
    _id,
    title,
    template,
    format,
    duration,
    width,
    height,
    cloudinaryUrl,
    cloudinaryPublicId,
    renderedAt,
    "posterUrl": variants[variantId == "site-poster-jpg"][0].url,
    "previewGifUrl": variants[variantId == "site-preview-gif"][0].url,
    "siteMp4Url": variants[variantId == "site-mp4"][0].url,
    ${VIDEO_VARIANTS_PROJECTION},
    "post": post->{title, slug}
  }
`);

/**
 * View types are derived from the TypeGen output (`apps/web/sanity.types.ts`,
 * regenerated by `pnpm typegen`) so they can never drift from the GROQ
 * projections above. Don't hand-edit these shapes — change the query and
 * re-run typegen.
 */
export type PostListItem = ALL_POSTS_QUERY_RESULT[number];
export type SinglePost = NonNullable<SINGLE_POST_QUERY_RESULT>;

// A post's ready video as projected by `SINGLE_POST_QUERY` (carries the
// audio-only `podcastUrl` from the podcast-mp3 variant; no back-ref to post).
export type PostVideo = SinglePost['videos'][number];

// A ready video as projected by `ALL_VIDEOS_QUERY` (carries a light back-ref to
// its post for the listing grid; no `podcastUrl`).
export type VideoListItem = ALL_VIDEOS_QUERY_RESULT[number];

// ── Podcast feed ────────────────────────────────────────────────────────────
// Narrated readings carrying a podcast-mp3 variant, newest first. Drives the
// RSS podcast feed at /feed.xml — the `podcast` fan-out surface as a real,
// subscribable channel rather than a one-off download.
export const PODCAST_FEED_QUERY = defineQuery(/* groq */ `
  *[_type == "video" && template == "article-narrated" && status == "ready" && count(variants[variantId == "podcast-mp3"]) > 0] | order(renderedAt desc){
    _id,
    title,
    duration,
    renderedAt,
    "audioUrl": variants[variantId == "podcast-mp3"][0].url,
    "post": post->{title, excerpt, "slug": slug.current}
  }
`);
export type PodcastFeedItem = PODCAST_FEED_QUERY_RESULT[number];

// ── Sitemap ─────────────────────────────────────────────────────────────────
// Every post with its primary ready video (if any), for the video-sitemap
// extension on /sitemap.xml so rendered videos are discoverable in search.
export const SITEMAP_QUERY = defineQuery(/* groq */ `
  *[_type == "post" && defined(slug.current)] | order(publishedAt desc){
    "slug": slug.current,
    title,
    excerpt,
    publishedAt,
    _updatedAt,
    "video": *[_type == "video" && post._ref == ^._id && status == "ready" && defined(cloudinaryUrl)] | order(renderedAt desc)[0]{
      title,
      cloudinaryUrl,
      "posterUrl": variants[variantId == "site-poster-jpg"][0].url
    }
  }
`);
export type SitemapEntry = SITEMAP_QUERY_RESULT[number];

// ── Captions ────────────────────────────────────────────────────────────────
// Narration chunks for one post — text + per-chunk duration reconstruct the
// WebVTT cue timings served at /posts/<slug>/captions.vtt.
export const POST_CAPTIONS_QUERY = defineQuery(/* groq */ `
  *[_type == "post" && slug.current == $slug][0]{
    "chunks": voiceoverChunks[]{text, durationSeconds}
  }
`);

// ── Playground ──────────────────────────────────────────────────────────────
// A handful of ready renders to seed the public Cloudinary transform playground.
export const PLAYGROUND_VIDEOS_QUERY = defineQuery(/* groq */ `
  *[_type == "video" && status == "ready" && defined(cloudinaryPublicId)] | order(renderedAt desc)[0...12]{
    _id,
    title,
    template,
    width,
    height,
    cloudinaryPublicId
  }
`);
export type PlaygroundVideo = PLAYGROUND_VIDEOS_QUERY_RESULT[number];

// Loads a newsletter doc with its hero video (variant URLs flattened to the top
// of the video projection) plus the optional linked post used for the CTA.
// Used by /api/newsletter/{preview,send}. The send route reads `_rev` for the
// optimistic-concurrency guard on the draft→sending transition.
// Shared projection for both query variants below — keeps the shape identical.
const NEWSLETTER_PROJECTION = /* groq */ `{
  _id,
  _rev,
  title,
  subject,
  previewText,
  intro,
  recipientSelection,
  status,
  sentAt,
  recipientCount,
  resendBroadcastId,
  video->{
    _id,
    title,
    cloudinaryPublicId,
    status,
    "gifUrl": variants[variantId == "site-preview-gif"][0].url,
    "posterUrl": variants[variantId == "site-poster-jpg"][0].url
  },
  post->{
    title,
    excerpt,
    "slug": slug.current,
    publishedAt,
    "authorName": author->name
  }
}`;

// Used by /api/newsletter/preview — relies on `perspective: 'drafts'` to find
// the in-progress doc. _id may be rewritten to the base form by the perspective.
export const NEWSLETTER_BY_ID_QUERY = defineQuery(/* groq */ `
  *[_type == "newsletter" && _id == $id][0]${NEWSLETTER_PROJECTION}
`);

// Used by /api/newsletter/send under `perspective: 'raw'`. Returns the actual
// storage _id (drafts.X or X) so the ifRevisionID patch targets the right doc.
// Order by _updatedAt so the draft (newer) wins when both exist.
export const NEWSLETTER_BY_EITHER_ID_QUERY = defineQuery(/* groq */ `
  *[_type == "newsletter" && _id in [$draftId, $baseId]] | order(_updatedAt desc)[0]${NEWSLETTER_PROJECTION}
`);

// Derived from TypeGen output. The byId and byEitherId queries share
// NEWSLETTER_PROJECTION, so their result types are identical — pick either.
export type NewsletterForSend = NonNullable<NEWSLETTER_BY_EITHER_ID_QUERY_RESULT>;
